config/routes.rb
Rails.application.routes.draw do
  resources :playlist_songs, only: [:new, :create, :destroy]
  resources :songs, only: [:index, :show]
  resources :artists, only: [:index, :show]
  resources :playlists
  resources :users, except: [:index]
  resources :favorites, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]

  get '/signup', to: 'users#new', as: 'signup'
  get '/', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions', to: 'sessions#destroy' 
  patch '/songs', to: 'songs#index', as: 'sort_songs'
  patch '/artists', to: 'artists#index', as: 'sort_artists'

  get '/about', to: 'sessions#about', as: 'about'
  patch '/playlists', to: 'playlists#index', as: 'sort_playlists'

  resources :songs, only: [:show] do
    resources :playlist_songs, only: [:new, :create]
  end

  resources :playlists, only: [:show] do
    resources :songs, only: [:show] do
      resources :playlist_songs, only: [:create]
    end
  end

end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs
    has_many :subscriptions
    has_many :users, through: :subscriptions

    def self.find_by_query(query_term)
        self.where("name LIKE ?", "%#{query_term}%")
    end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    def index
        @query = params[:query]
        if @query
            @artists = Artist.find_by_query(@query) 
        else
            @artists = Artist.all
        end

        if params[:sort] == "popularity"
            @artists = @artists.sort_by {|artist| artist.subscriptions.length}.reverse
        elsif params[:sort] == "a-z"
            @artists = @artists.sort_by {|artist| artist.name}
        elsif params[:sort] == "z-a"
            @artists = @artists.sort_by {|artist| artist.name}.reverse
        end
    end

    def show
        @artist = Artist.find(params[:id])
        @songs = @artist.songs
        @subscription = Subscription.find_by(artist:@artist, user:current_user)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>

<div class="search">
    <%= form_tag artists_path, method: :get do %>
        <%= text_field_tag :query, params[:query], placeholder: "Search by Artist" %>
        <%= submit_tag "Search" %>
    <% end %>
</div>

<div class="button sort">
    <%= button_to "Sort by popularity", sort_artists_path, method: :patch, params: {sort: "popularity", query: @query} %>
    <%= button_to "Sort by name (A-Z)", sort_artists_path, method: :patch, params: {sort: "a-z", query: @query} %>
    <%= button_to "Sort by name (Z-A)", sort_artists_path, method: :patch, params: {sort: "z-a", query: @query} %>
</div>
<br>
<br>
<div class="grid">
    <% @artists.each do |artist| %>
        <div> 
            <%= form_tag artist_path(artist), method: :get do  %>
                <%= image_submit_tag artist.image %>
            <% end %>
            <p class="artistName"><%= link_to artist.name, artist %></p>
            <br>
        </div>
    <% end %>
</div>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<div id="artist-show">
    <div class="toggle">
        <% if @subscription %>
            <%= button_to "Unsubscribe", @subscription, method: :delete, "class" => "subBtn" %>
        <% else %>   
            <%= button_to "Subscribe", subscriptions_path, method: :post, params: {artist_id: @artist.id}, "class" => "subBtn" %>
        <% end %> 
    </div>
    <div>
        <%=pluralize(@artist.subscriptions.length, "subscriber")%>
    </div>

    <br>

    <img src="<%=@artist.image%>" alt="<%=@artist.name%>" style="width:300px;height:300px;">
    <div>
        <% @songs.each do |song| %>
            <p><%= link_to song.title, song %></p>
        <% end %>
    </div>
</div>