config/routes.rb
Rails.application.routes.draw do
  resources :playlist_songs, only: [:new, :create, :destroy]
  resources :songs, only: [:index, :show]
  resources :artists, only: [:index, :show]
  resources :playlists
  resources :users, except: [:index]
  resources :favorites, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]

  get '/signup', to: 'users#new', as: 'signup'
  get '/', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions', to: 'sessions#destroy' 
  patch '/songs', to: 'songs#index', as: 'sort_songs'
  patch '/artists', to: 'artists#index', as: 'sort_artists'

  get '/about', to: 'sessions#about', as: 'about'
  patch '/playlists', to: 'playlists#index', as: 'sort_playlists'

  resources :songs, only: [:show] do
    resources :playlist_songs, only: [:new, :create]
  end

  resources :playlists, only: [:show] do
    resources :songs, only: [:show] do
      resources :playlist_songs, only: [:create]
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :playlists, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :subscriptions, dependent: :destroy
    has_many :artists, through: :subscriptions
    validates :username, uniqueness:true, length:{in: 4..12}
    validates :username, :name, :password, presence:true
    validates :username, format: { with: /\A[a-zA-Z0-9]+\z/,
    message: "only allows letters and numbers" }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]
    before_action :get_user, only:[:show, :edit, :update, :destroy]


    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def edit
    end
    
    def update
        if @user.update(user_params)
            flash[:success] = "Successfully updated!"
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    def destroy
        @user.destroy
        session.clear
        redirect_to '/'
    end

    private

    def get_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name, :username, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="signup_page">
    <ul>
    <% if @user.errors.any?%>
        <% @user.errors.full_messages.each do |msg|%>
            <li class="danger" ><%= msg %></li>
        <%end%>
    <%end%>
    </ul>
    <div class="signup_form">
        <%=form_for @user do |f|%>
        <%=f.label :name%><br/>
        <%=f.text_field :name%><br/>
      <br/>
      <%=f.label :username%><br/>
        <%=f.text_field :username%><br/>
        <br/>
        <%=f.label :password%><br/>
        <%=f.password_field :password%><br/>
       <br/>
        <%=f.label :password_confirmation %><br/>
        <%=f.password_field :password_confirmation %><br/>
        <br/>
        <div id="update_btn">
        <%=f.submit%>
        <% end %>
        <br>
        <br>
    <div class="login_edit">
       <% if logged_in?%>
       <%=button_to 'Delete this account', current_user, method: :delete, data:{confirm: 'Are you sure you want to permanently delete this account?'}%>
       <% else %>
       <%=button_to "Back to Login", login_path, method: :get%>
       <% end %>
    </div>
        </div>
    </div>
    <br/>
</div>

app/views/users/edit.html.erb
<h1> Edit your SAMtify account! </h1>
<%= render 'form'%><br/>

app/views/users/new.html.erb
<h1> Create a SAMtify account! </h1>
<%= render 'form'%><br/>
<%# <br/> %>
 

app/views/users/show.html.erb
<div class="grid">

<!-- show page for other users -->
<% if @user != current_user %>
    <div class="welcome">
        <h1><%= @user.name%>'s Playlists</h1>
    </div>
    <div class="user_favorites">
        <% @user.playlists.each do |playlist| %>
            <div class="playlist-text"><%= link_to playlist.name, playlist %></div>
        <% end %>
        
    </div>
    <br>
    <div class="button viewPlaylists">
        <%= button_to 'View All Playlists', playlists_path, method: :get %><br/>
    </div>
    
    

<!-- show page for current user -->
<% else %>
        <div class="welcome">
            <h1>Welcome, <%= current_user.name %>!</h1>
        </div>
        <div class="user_playlists"> 
            <h2 class="userShowLabel">My Playlists</h2>
            <% current_user.playlists.each do |playlist| %>
                <div class="playlist-text"><%= link_to playlist.name, playlist %></div>
            <% end %>
        </div>

        <br>
        <div class="user_favorites"> 
            <h2 class="userShowLabel">My Favorites</h2>
            <% current_user.favorites.each do |favorite| %>
                <div class="playlist-text"><%= link_to favorite.playlist.name, favorite.playlist %></div>
            <% end %>
        </div>
        <br>

        <div class="user_subscriptions">
            <h2 class="userShowLabel">Subscriptions</h2>
            <% current_user.subscriptions.each do |sub| %>
                <div class="playlist-text"><%= link_to sub.artist.name, artist_path(sub.artist) %></div>
            <% end %>
        </div>
        <br>
            
        <div class="button">
            <%= button_to 'Create a New Playlist', new_playlist_path, method: :get %><br/>
        </div>
        <div class="button" id="b1">
            <%= button_to 'View All Playlists', playlists_path, method: :get %><br/>
        </div>
        <div class="button" id="b2">
            <%= button_to 'View All Artists', artists_path, method: :get %><br/>
        </div>

   
    
<% end %>

 </div>