config/routes.rb
Rails.application.routes.draw do
  resources :playlist_songs, only: [:new, :create, :destroy]
  resources :songs, only: [:index, :show]
  resources :artists, only: [:index, :show]
  resources :playlists
  resources :users, except: [:index]
  resources :favorites, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]

  get '/signup', to: 'users#new', as: 'signup'
  get '/', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions', to: 'sessions#destroy' 
  patch '/songs', to: 'songs#index', as: 'sort_songs'
  patch '/artists', to: 'artists#index', as: 'sort_artists'

  get '/about', to: 'sessions#about', as: 'about'
  patch '/playlists', to: 'playlists#index', as: 'sort_playlists'

  resources :songs, only: [:show] do
    resources :playlist_songs, only: [:new, :create]
  end

  resources :playlists, only: [:show] do
    resources :songs, only: [:show] do
      resources :playlist_songs, only: [:create]
    end
  end

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs

  def self.find_by_query(query_term)
    self.where("title LIKE ?", "%#{query_term}%")
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    
    def index
        @playlist_id = params[:playlist_id]
        @query = params[:query]
        if params[:query]
            @songs = Song.find_by_query(params[:query]).to_a
            artists = Artist.find_by_query(params[:query])
            artist_songs = artists.map {|artist| artist.songs}.flatten
            artist_songs.each {|song| @songs << song}
            @songs = @songs.uniq
        else
            @songs = Song.all
        end

        if params[:sort] == "popularity"
            @songs = @songs.sort_by {|song| song.playlists.count}.reverse
        elsif params[:sort] == "a-z"
            @songs = @songs.sort_by {|song| song.title}
        elsif params[:sort] == "z-a"
            @songs = @songs.sort_by {|song| song.title}.reverse
        end
    end

    def show
        @song = Song.find(params[:id])
        if params[:playlist_id] && params[:playlist_id] != ""
            @playlist_id = params[:playlist_id]
        end
    end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/index.html.erb
<h1>Songs</h1>

<div class="search">
    <%= form_tag songs_path, method: :get do %>
        <%= hidden_field_tag :playlist_id, @playlist_id %>
        <%= text_field_tag :query, params[:query], placeholder: "Search by Song" %>
        <%= submit_tag "Search" %>
    <% end %>
</div>
<div class="button sort">
    <%= button_to "Sort by popularity", sort_songs_path, method: :patch, params: {sort: "popularity", playlist_id: @playlist_id, query: @query} %>
    <%= button_to "Sort by name (A-Z)", sort_songs_path, method: :patch, params: {sort: "a-z", playlist_id: @playlist_id, query: @query} %>
    <%= button_to "Sort by name (Z-A)", sort_songs_path, method: :patch, params: {sort: "z-a", playlist_id: @playlist_id, query: @query} %>
</div>
<br>
<br>
<div class="grid">
    <% @songs.each do |song| %>
        <div>
            <%= form_tag song_path(song), method: :get do  %>
                <%= hidden_field_tag :playlist_id, @playlist_id %>
                <%= image_submit_tag song.image %>
            <% end %>
            <%= link_to "<p id=\"songTitle\">#{song.title}</p><p class=\"artistName\">#{song.artist.name}</p>".html_safe, song_path(id: song.id, playlist_id: @playlist_id) %>
            <br>
        </div>
    <% end %>
</div>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<h2><%= link_to @song.artist.name, @song.artist %></h2>
<br>
<div id="song-show">
  <div>
    <img src="<%=@song.image%>" alt="<%=@song.title%>" style="width:300px;height:300px;">
  </div>
  <br>
  <div>
    <audio controls loop>
      <source src="<%=@song.preview%>" type="audio/ogg">
      Your browser does not support the audio tag.
    </audio>
    <br><br>
    <% if current_user.playlists.count != 0 %>
      <% if @playlist_id %>
          <%= button_to "Add to Playlist", playlist_song_playlist_songs_path(playlist_id: @playlist_id, song_id: @song.id), method: :post %>
      <% else %>
          <%= button_to "Add to Playlist", new_song_playlist_song_path(@song.id), method: :get%>
      <% end %>
    <% end %>
  </div>
</div>