config/routes.rb
Rails.application.routes.draw do
  resources :playlist_songs, only: [:new, :create, :destroy]
  resources :songs, only: [:index, :show]
  resources :artists, only: [:index, :show]
  resources :playlists
  resources :users, except: [:index]
  resources :favorites, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]

  get '/signup', to: 'users#new', as: 'signup'
  get '/', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions', to: 'sessions#destroy' 
  patch '/songs', to: 'songs#index', as: 'sort_songs'
  patch '/artists', to: 'artists#index', as: 'sort_artists'

  get '/about', to: 'sessions#about', as: 'about'
  patch '/playlists', to: 'playlists#index', as: 'sort_playlists'

  resources :songs, only: [:show] do
    resources :playlist_songs, only: [:new, :create]
  end

  resources :playlists, only: [:show] do
    resources :songs, only: [:show] do
      resources :playlist_songs, only: [:create]
    end
  end

end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :playlist_songs, dependent: :destroy
  has_many :songs, through: :playlist_songs
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: {scope: :user}

  def self.find_by_query(query_term)
    self.where("name LIKE ?", "%#{query_term}%")
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    before_action :get_playlist, only: [:show, :edit, :update, :destroy]

    def index
        @query = params[:query]
        if @query
            @playlists = Playlist.find_by_query(@query)
        else
            @playlists = Playlist.all
        end

        if params[:sort] == "popularity"
            @playlists = @playlists.sort_by {|playlist| playlist.favorites.count}.reverse
        elsif params[:sort] == "a-z"
            @playlists = @playlists.sort_by {|playlist| playlist.name.downcase}
        elsif params[:sort] == "z-a"
            @playlists = @playlists.sort_by {|playlist| playlist.name.downcase}.reverse
        end

    end

    def show
        @songs = @playlist.playlist_songs.map {|ps| ps.song }    
        @favorite = Favorite.find_by(playlist_id: params[:id], user_id: current_user.id)
    end
    
    def new
        @playlist = Playlist.new
    end

    def create
        @playlist = Playlist.new(user_id: current_user.id, name: params[:playlist][:name])
        if @playlist.save
            redirect_to @playlist
        else
            render :new
        end
    end

    def edit
        if !is_authorized?
            not_authorized
        end
    end

    def update
        if @playlist.update(name: params[:playlist][:name])
            redirect_to @playlist
        else 
            render :edit
        end
    end

    def destroy
        if !is_authorized?
            not_authorized
        else
            @playlist.destroy
            redirect_to playlists_path
        end
    end

    private

    def get_playlist
        @playlist = Playlist.find(params[:id])
    end

    def playlist_params
        params.require(:playlist).permit(:name, :user_id)
    end

    def is_authorized?
        @playlist.user == current_user
    end

    def not_authorized
        redirect_to playlists_path
        flash[:danger] = "You don't own this playlist!"
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<div class ="new_playlist">
        <% if playlist.errors.any? %>
        <% playlist.errors.full_messages.each do |m| %>
                <p class="danger"><%= m %></p>
            <% end %>
        <% end %>
    <div class ="new_playlist_form">
    <%= form_for playlist do |f| %>
        <%= f.text_field :name, placeholder:"Playlist Name"%>
        
      <%= f.submit %>
    <% end %><br/>
    <% if current_user.playlists.include?(playlist)%>
        <%= button_to "Delete Playlist", playlist_path(playlist), method: :delete, data: {confirm: "Are you sure you want to delete this playlist?"} %>
    <%end%>
    </div>

</div>

app/views/playlists/edit.html.erb
<h1> Edit Playlist </h1>

<%= render partial: 'form', locals: {playlist: @playlist} %>

 

app/views/playlists/index.html.erb
<h1> All Playlists </h1>
<div class="search">
    <%= form_tag playlists_path, method: :get do %>
        <%= text_field_tag :query, params[:query], placeholder: "Search for playlist" %>
        <%= submit_tag "Search" %>
    <% end %>
</div>
<div class="button sort">
    <%= button_to "Sort by popularity", sort_playlists_path, method: :patch, params: {sort: "popularity", query: @query} %>
    <%= button_to "Sort by name (A-Z)", sort_playlists_path, method: :patch, params: {sort: "a-z", query: @query} %>
    <%= button_to "Sort by name (Z-A)", sort_playlists_path, method: :patch, params: {sort: "z-a", query: @query} %>
</div>
<br>
<br>
<table>
    <tr>
        <th>Playlist</th>
        <th>User</th>
        <th></th>
    </tr>
    <% @playlists.each do |p| %>
        <tr class="playlist-text">
            <td><%= link_to p.name, p %></td>
            <td><%= link_to p.user.username, p.user %></td>
            <td class="toggle">
                <% favorite = current_user.favorites.find {|fav| fav.playlist == p} %>
                <% if favorite %>
                    <%= button_to "Unfavorite", favorite, method: :delete %>
                <% else %>
                    <%= button_to "Favorite", favorites_path, method: :post, params: {playlist_id: p.id} %>
                <% end %>
            </td>
        </tr>
    <% end %>
</table>
<br>
<div class="button">
    <%= button_to "Create a Playlist", new_playlist_path, method: :get %>
</div>

app/views/playlists/new.html.erb
<h1>Create a Playlist</h1>

<%= render partial: 'form', locals: {playlist: @playlist} %>

app/views/playlists/show.html.erb
<div class="playlist_show">
    <div class="playlist_title">
    <h1><%= @playlist.name %></h1>
    <h5>
        <div class="toggle">
            <% if @favorite %>
                <%= button_to "Unfavorite", @favorite, method: :delete, params: {toggle: true}, "class" => "subBtn" %>
            <% else %>   
                <%= button_to "Favorite", favorites_path, method: :post, params: {toggle: true, playlist_id: @playlist.id}, "class" => "subBtn" %>
            <% end %> 
        </div>

        By <%= link_to @playlist.user.name, @playlist.user %>
        <br><br>
        Songs: <%= @songs.count %>
        <br>
        Favorites: <%= @playlist.favorites.count %>
    </h5>
    </div>


    
    <table class="song_text">
    <tr>
        <th> Song </th>
        <th> Artist </th>
        <th> Play </th>
        <th> </th>
    </tr>
        <% @songs.each do |song| %> 
    <tr>
            <td><%= link_to song.title, song %></td>
            <td><%= link_to song.artist.name, song.artist %></td>
            <td><audio controls id="audio" >
            <source src="<%=song.preview%>" type="audio/ogg">
            Your browser does not support the audio tag.
            </audio></td>
            <td><% if @playlist.user == current_user %>
                <%= link_to "Delete", PlaylistSong.find_by(song_id: song.id, playlist_id: @playlist.id), method: :delete %>
                <% end %></td>
    </tr>
        <% end %>
    </table>
</div>
<br/>
    <div class="button">
    <% if @playlist.user == current_user %>
        <%= button_to "Add Songs", songs_path, method: :get, params: {playlist_id: @playlist.id} %><br>
        <%= button_to "Edit Playlist", edit_playlist_path(@playlist), method: :get %>
    <% end %>
    </div>